### ISSUE TITLE
Optimistic locking failure

### ISSUE THREAD

**Issue by dellermann** [dellermann/springcrm#12]
I get an optimistic locking failure when displaying an invoice in the show view
(see error report).
# Error report

``` xml
<?xml version="1.0"?>

<error-report xmlns="http://www.amc-world.de/data/xml/springcrm"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.amc-world.de/data/xml/springcrm http://www.amc-world.de/data/xml/springcrm/error-report-1.1.xsd">
  <report-version>1.1</report-version>
  <application>
    <version>1.2.3</version>
    <build-number>1289</build-number>
    <build-date>2012-08-25T00:09:04+0200</build-date>
    <build-profile>live</build-profile>
  </application>
  <customer>
    <name>Daniel Ellermann</name>
    <email>d.ellermann@amc-world.de</email>
  </customer>
  <description>Beim Aufruf einer Rechnung in der Show-View.</description>
  <details>
    <status-code>500</status-code>
    <message>Object of class [org.amcworld.springcrm.User] with identifier [1]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [org.amcworld.springcrm.User#1]</message>
    <servlet>grails</servlet>
    <uri>/springcrm/grails/invoice/list.dispatch</uri>
  </details>
  <exception>
    <message>Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [org.amcworld.springcrm.User#1]</message>
    <caused-by>Object of class [org.amcworld.springcrm.User] with identifier [1]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [org.amcworld.springcrm.User#1]</caused-by>
    <class-name>ViewFilters</class-name>
    <line-number>71</line-number>
    <code-snippet>

    </code-snippet>
    <stack-trace>
    org.springframework.orm.hibernate3.HibernateOptimisticLockingFailureException: Object of class [org.amcworld.springcrm.User] with identifier [1]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [org.amcworld.springcrm.User#1]
    at org.amcworld.springcrm.ViewFilters$_closure1_closure2_closure7.doCall(ViewFilters.groovy:71)
    at java.lang.Thread.run(Thread.java:662)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [org.amcworld.springcrm.User#1]
    ... 2 more
    </stack-trace>
  </exception>
</error-report>
```

_Related to Bugzilla bug 262._

**Comment by dellermann** [comment]
This bug has no longer been observed in SpringCRM 1.5 and higher.
