### ISSUE TITLE
Exception while searching

### ISSUE THREAD

**Issue by dellermann** [dellermann/springcrm#23]
I search for the term "Euroregion" and get an exception:

``` xml
<?xml version="1.0"?>

  <error-report xmlns="http://www.amc-world.de/data/xml/springcrm"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.amc-world.de/data/xml/springcrm http://www.amc-world.de/data/xml/springcrm/error-report-1.1.xsd">
    <report-version>1.1</report-version>
    <application>
      <version>1.4.5</version>
      <build-number>5037</build-number>
      <build-date>2013-12-04T18:36:35+0100</build-date>
      <build-profile>production</build-profile>
    </application>
    <customer>
      <name>Daniel Ellermann</name>
      <email>d.ellermann@amc-world.de</email>
    </customer>
    <description>Bei der Suche nach dem Begriff „Euroregion“.</description>
    <details>
      <status-code>500</status-code>
      <message>Executing action [index] of controller [grails.plugin.searchable.SearchableController] in plugin [searchable] caused exception: Runtime error executing action</message>
      <servlet>grails</servlet>
      <uri>/springcrm/grails/searchable/index.dispatch</uri>
    </details>
    <exception>
      <message>field "number" does not appear to be indexed</message>
      <caused-by>field "number" does not appear to be indexed</caused-by>
      <class-name>SearchableController</class-name>
      <line-number>36</line-number>
      <code-snippet>

      </code-snippet>
      <stack-trace>
      java.lang.RuntimeException: field "number" does not appear to be indexed
    at org.apache.lucene.search.ExtendedFieldCacheImpl$5.createValue(ExtendedFieldCacheImpl.java:173)
    at org.apache.lucene.search.FieldCacheImpl$Cache.get(FieldCacheImpl.java:71)
    at org.apache.lucene.search.ExtendedFieldCacheImpl.getAuto(ExtendedFieldCacheImpl.java:127)
    at org.apache.lucene.search.FieldSortedHitQueue.comparatorAuto(FieldSortedHitQueue.java:487)
    at org.apache.lucene.search.FieldSortedHitQueue$1.createValue(FieldSortedHitQueue.java:184)
    at org.apache.lucene.search.FieldCacheImpl$Cache.get(FieldCacheImpl.java:71)
    at org.apache.lucene.search.FieldSortedHitQueue.getCachedComparator(FieldSortedHitQueue.java:167)
    at org.apache.lucene.search.FieldSortedHitQueue.<init>(FieldSortedHitQueue.java:55)
    at org.apache.lucene.search.TopFieldDocCollector.<init>(TopFieldDocCollector.java:43)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:121)
    at org.apache.lucene.search.MultiSearcher.search(MultiSearcher.java:232)
    at org.apache.lucene.search.Hits.getMoreDocs(Hits.java:113)
    at org.apache.lucene.search.Hits.<init>(Hits.java:90)
    at org.apache.lucene.search.Searcher.search(Searcher.java:61)
    at org.compass.core.lucene.engine.transaction.support.AbstractTransactionProcessor.findByQuery(AbstractTransactionProcessor.java:146)
    at org.compass.core.lucene.engine.transaction.readcommitted.ReadCommittedTransactionProcessor.doFind(ReadCommittedTransactionProcessor.java:259)
    at org.compass.core.lucene.engine.transaction.support.AbstractConcurrentTransactionProcessor.find(AbstractConcurrentTransactionProcessor.java:246)
    at org.compass.core.lucene.engine.LuceneSearchEngine.find(LuceneSearchEngine.java:352)
    at org.compass.core.lucene.engine.LuceneSearchEngineQuery.hits(LuceneSearchEngineQuery.java:188)
    at org.compass.core.impl.DefaultCompassQuery.hits(DefaultCompassQuery.java:199)
    at grails.plugin.searchable.internal.compass.search.DefaultSearchMethod$SearchCompassCallback.doInCompass(DefaultSearchMethod.java:109)
    at org.compass.core.CompassTemplate.execute(CompassTemplate.java:133)
    at grails.plugin.searchable.internal.compass.support.AbstractSearchableMethod.doInCompass(AbstractSearchableMethod.java:56)
    at grails.plugin.searchable.internal.compass.search.DefaultSearchMethod.invoke(DefaultSearchMethod.java:71)
    at grails.plugin.searchable.SearchableService.search(SearchableService.groovy:39)
    at grails.plugin.searchable.SearchableController$_closure1.doCall(SearchableController.groovy:36)
      </stack-trace>
    </exception>
  </error-report>
```

**Comment by dellermann** [comment]
Now, this exception occurred. Here the field "name" is not indexed.

``` xml
<?xml version="1.0"?>

  <error-report xmlns="http://www.amc-world.de/data/xml/springcrm"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.amc-world.de/data/xml/springcrm http://www.amc-world.de/data/xml/springcrm/error-report-1.1.xsd">
    <report-version>1.1</report-version>
    <application>
      <version>1.4.5</version>
      <build-number>5089</build-number>
      <build-date>2013-12-20T14:32:28+0100</build-date>
      <build-profile>production</build-profile>
    </application>
    <customer>
      <name>Daniel Ellermann</name>
      <email>d.ellermann@amc-world.de</email>
    </customer>
    <description>Diesmal bei der Suche nach "Tai".</description>
    <details>
      <status-code>500</status-code>
      <message>Executing action [index] of controller [grails.plugin.searchable.SearchableController] in plugin [searchable] caused exception: Runtime error executing action</message>
      <servlet>grails</servlet>
      <uri>/springcrm/grails/searchable/index.dispatch</uri>
    </details>
    <exception>
      <message>field "name" does not appear to be indexed</message>
      <caused-by>field "name" does not appear to be indexed</caused-by>
      <class-name>SearchableController</class-name>
      <line-number>36</line-number>
      <code-snippet>

      </code-snippet>
      <stack-trace>
      java.lang.RuntimeException: field "name" does not appear to be indexed
    at org.apache.lucene.search.ExtendedFieldCacheImpl$5.createValue(ExtendedFieldCacheImpl.java:173)
    at org.apache.lucene.search.FieldCacheImpl$Cache.get(FieldCacheImpl.java:71)
    at org.apache.lucene.search.ExtendedFieldCacheImpl.getAuto(ExtendedFieldCacheImpl.java:127)
    at org.apache.lucene.search.FieldSortedHitQueue.comparatorAuto(FieldSortedHitQueue.java:487)
    at org.apache.lucene.search.FieldSortedHitQueue$1.createValue(FieldSortedHitQueue.java:184)
    at org.apache.lucene.search.FieldCacheImpl$Cache.get(FieldCacheImpl.java:71)
    at org.apache.lucene.search.FieldSortedHitQueue.getCachedComparator(FieldSortedHitQueue.java:167)
    at org.apache.lucene.search.FieldSortedHitQueue.<init>(FieldSortedHitQueue.java:55)
    at org.apache.lucene.search.TopFieldDocCollector.<init>(TopFieldDocCollector.java:43)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:121)
    at org.apache.lucene.search.MultiSearcher.search(MultiSearcher.java:232)
    at org.apache.lucene.search.Hits.getMoreDocs(Hits.java:113)
    at org.apache.lucene.search.Hits.<init>(Hits.java:90)
    at org.apache.lucene.search.Searcher.search(Searcher.java:61)
    at org.compass.core.lucene.engine.transaction.support.AbstractTransactionProcessor.findByQuery(AbstractTransactionProcessor.java:146)
    at org.compass.core.lucene.engine.transaction.readcommitted.ReadCommittedTransactionProcessor.doFind(ReadCommittedTransactionProcessor.java:259)
    at org.compass.core.lucene.engine.transaction.support.AbstractConcurrentTransactionProcessor.find(AbstractConcurrentTransactionProcessor.java:246)
    at org.compass.core.lucene.engine.LuceneSearchEngine.find(LuceneSearchEngine.java:352)
    at org.compass.core.lucene.engine.LuceneSearchEngineQuery.hits(LuceneSearchEngineQuery.java:188)
    at org.compass.core.impl.DefaultCompassQuery.hits(DefaultCompassQuery.java:199)
    at grails.plugin.searchable.internal.compass.search.DefaultSearchMethod$SearchCompassCallback.doInCompass(DefaultSearchMethod.java:109)
    at org.compass.core.CompassTemplate.execute(CompassTemplate.java:133)
    at grails.plugin.searchable.internal.compass.support.AbstractSearchableMethod.doInCompass(AbstractSearchableMethod.java:56)
    at grails.plugin.searchable.internal.compass.search.DefaultSearchMethod.invoke(DefaultSearchMethod.java:71)
    at grails.plugin.searchable.SearchableService.search(SearchableService.groovy:39)
    at grails.plugin.searchable.SearchableController$_closure1.doCall(SearchableController.groovy:36)
      </stack-trace>
    </exception>
  </error-report>
```

**Comment by dellermann** [comment]
Maybe this bug is related to issue #25. If the indexer didn't work correctly and doesn't include all needed properties into the index this bug may arise. We should observe this.

**Comment by dellermann** [comment]
I close this issue because it doesn't occur any longer.
