### ISSUE TITLE
Cannot save sequence numbers

### ISSUE THREAD

**Issue by dellermann** [dellermann/springcrm#48]
When trying to save sequence numbers in the settings area I get the following error message:

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '15000' with class 'java.lang.String' to class 'int'
    at org.amcworld.springcrm.ConfigController.saveSeqNumbers(ConfigController.groovy:247)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dellermann** [comment]
Fixed in commit 673993f.
