### ISSUE TITLE
Submitting a form with payment amount will result in error

### ISSUE THREAD

**Issue by philipdrozd** [dellermann/springcrm#51]
Forms which require to specify a payment amount (such as invoice) result in the error 'Unable to parse number' on submit and will eventually redirect you to the default error page.
### Stacktrace:

```
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:applyLayout>: Error executing tag <f:display>: Cannot get property 'widget' on null object
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:applyLayout>: Error executing tag <f:display>: Cannot get property 'widget' on null object
    at home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp$_run_closure2.doCall(home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp:172)
    at home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp.run(home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp:237)
    ... 3 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <f:display>: Cannot get property 'widget' on null object
    at home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp$_run_closure2_closure14.doCall(home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp:121)
    ... 5 more
Caused by: java.lang.NullPointerException: Cannot get property 'widget' on null object
    at grails.plugin.formfields.FormFieldsTemplateService.getWidget(FormFieldsTemplateService.groovy:131)
    at grails.plugin.formfields.FormFieldsTemplateService.candidateTemplatePaths(FormFieldsTemplateService.groovy:102)
    at grails.plugin.formfields.FormFieldsTemplateService.findTemplateCacheable(FormFieldsTemplateService.groovy:44)
    at grails.plugin.formfields.FormFieldsTemplateService.findTemplate(FormFieldsTemplateService.groovy:37)
    at grails.plugin.formfields.FormFieldsTagLib.renderForDisplay(FormFieldsTagLib.groovy:214)
    at grails.plugin.formfields.FormFieldsTagLib$_closure5.doCall(FormFieldsTagLib.groovy:168)
    ... 6 more
```

![zahlungsbetrag-bug](https://cloud.githubusercontent.com/assets/13121869/8486166/24d056f4-2103-11e5-83d0-2b7ac5b84dce.png)

**Comment by dellermann** [comment]
Fixed in commit f0696eca0a65f85586fe36fef8bfd1424007ff31.
