### ISSUE TITLE
Customers view on Helpdesk will cause error

### ISSUE THREAD

**Issue by philipdrozd** [dellermann/springcrm#53]
When clicking the customers view ('Kundenansicht') button one will encounter an error.
### Stacktrace

```
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : frontend
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <asset:stylesheet>: No signature of method: static asset.pipeline.AssetHelper.nameWithoutExtension() is applicable for argument types: (org.codehaus.groovy.grails.web.util.StreamCharBuffer) values: [helpdesk-frontend]
Possible solutions: nameWithoutExtension(java.lang.String)
    ... 3 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <asset:stylesheet>: No signature of method: static asset.pipeline.AssetHelper.nameWithoutExtension() is applicable for argument types: (org.codehaus.groovy.grails.web.util.StreamCharBuffer) values: [helpdesk-frontend]
Possible solutions: nameWithoutExtension(java.lang.String)
    at home_pdrozd_Projekte_springcrm_grails_app_views_layouts_frontend_gsp$_run_closure8.doCall(home_pdrozd_Projekte_springcrm_grails_app_views_layouts_frontend_gsp:41)
    at home_pdrozd_Projekte_springcrm_grails_app_views_layouts_frontend_gsp.run(home_pdrozd_Projekte_springcrm_grails_app_views_layouts_frontend_gsp:56)
    ... 3 more
Caused by: groovy.lang.MissingMethodException: No signature of method: static asset.pipeline.AssetHelper.nameWithoutExtension() is applicable for argument types: (org.codehaus.groovy.grails.web.util.StreamCharBuffer) values: [helpdesk-frontend]
Possible solutions: nameWithoutExtension(java.lang.String)
    at asset.pipeline.grails.AssetsTagLib$_closure2.doCall(AssetsTagLib.groovy:62)
    ... 5 more
```

![anwendungsfehler-bei-kundenansicht](https://cloud.githubusercontent.com/assets/13121869/8486370/6f556844-2104-11e5-9c36-e46b8a0388a8.png)

**Comment by dellermann** [comment]
Fixed in commit 847821cc21a89f20b6c64383c7365c1e758d0d93.
