### ISSUE TITLE
Clicking an invoice via panel will result in error

### ISSUE THREAD

**Issue by philipdrozd** [dellermann/springcrm#62]
When trying to open an invoice via the panel on the landing page, one will ecounter an error before getting redirected to the error page (Anwendungsfehler).
Editing an invoice via panel works.
### Stacktrace

```
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:applyLayout>: Error executing tag <f:display>: Cannot get property 'widget' on null object
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:applyLayout>: Error executing tag <f:display>: Cannot get property 'widget' on null object
    at home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp$_run_closure2.doCall(home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp:172)
    at home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp.run(home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp:237)
    ... 3 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <f:display>: Cannot get property 'widget' on null object
    at home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp$_run_closure2_closure14.doCall(home_pdrozd_Projekte_springcrm_grails_app_views_invoice_show_gsp:121)
    ... 5 more
Caused by: java.lang.NullPointerException: Cannot get property 'widget' on null object
    at grails.plugin.formfields.FormFieldsTemplateService.getWidget(FormFieldsTemplateService.groovy:131)
    at grails.plugin.formfields.FormFieldsTemplateService.candidateTemplatePaths(FormFieldsTemplateService.groovy:102)
    at grails.plugin.formfields.FormFieldsTemplateService.findTemplateCacheable(FormFieldsTemplateService.groovy:44)
    at grails.plugin.formfields.FormFieldsTemplateService.findTemplate(FormFieldsTemplateService.groovy:37)
    at grails.plugin.formfields.FormFieldsTagLib.renderForDisplay(FormFieldsTagLib.groovy:214)
    at grails.plugin.formfields.FormFieldsTagLib$_closure5.doCall(FormFieldsTagLib.groovy:168)
    ... 6 more
```

**Comment by dellermann** [comment]
Cannot reproduce this issue.
