### ISSUE TITLE
searchable plugin issues

### ISSUE THREAD

**Issue by dellermann** [dellermann/springcrm#63]
Regularly problems arise when using the search via searchable plugin. For example, a particular field does not appear to be indexed:

``` xml
<?xml version="1.0"?>

<error-report xmlns="http://www.amc-world.de/data/xml/springcrm"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.amc-world.de/data/xml/springcrm http://www.amc-world.de/data/xml/springcrm/error-report-1.1.xsd">
  <report-version>1.1</report-version>
  <application>
    <version>1.5.2</version>
    <build-number>7829</build-number>
    <build-date>2015-01-17T17:20:19+0100</build-date>
    <build-profile>production</build-profile>
  </application>
  <customer>
    <name>Robert</name>
    <email></email>
  </customer>
  <description></description>
  <details>
    <status-code>500</status-code>
    <message>Executing action [index] of controller [grails.plugin.searchable.SearchableController] in plugin [searchable] caused exception: Runtime error executing action</message>
    <servlet>grails</servlet>
    <uri>/springcrm/grails/searchable/index.dispatch</uri>
  </details>
  <exception>
    <message>field "docDate" does not appear to be indexed</message>
    <caused-by>field "docDate" does not appear to be indexed</caused-by>
    <class-name>SearchableController</class-name>
    <line-number>36</line-number>
    <code-snippet>

    </code-snippet>
    <stack-trace>
    java.lang.RuntimeException: field "docDate" does not appear to be indexed
    at org.apache.lucene.search.ExtendedFieldCacheImpl$5.createValue(ExtendedFieldCacheImpl.java:173)
    at org.apache.lucene.search.FieldCacheImpl$Cache.get(FieldCacheImpl.java:71)
    at org.apache.lucene.search.ExtendedFieldCacheImpl.getAuto(ExtendedFieldCacheImpl.java:127)
    at org.apache.lucene.search.FieldSortedHitQueue.comparatorAuto(FieldSortedHitQueue.java:487)
    at org.apache.lucene.search.FieldSortedHitQueue$1.createValue(FieldSortedHitQueue.java:184)
    at org.apache.lucene.search.FieldCacheImpl$Cache.get(FieldCacheImpl.java:71)
    at org.apache.lucene.search.FieldSortedHitQueue.getCachedComparator(FieldSortedHitQueue.java:167)
    at org.apache.lucene.search.FieldSortedHitQueue.<init>(FieldSortedHitQueue.java:55)
    at org.apache.lucene.search.TopFieldDocCollector.<init>(TopFieldDocCollector.java:43)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:121)
    at org.apache.lucene.search.MultiSearcher.search(MultiSearcher.java:232)
    at org.apache.lucene.search.Hits.getMoreDocs(Hits.java:113)
    at org.apache.lucene.search.Hits.<init>(Hits.java:90)
    at org.apache.lucene.search.Searcher.search(Searcher.java:61)
    at org.compass.core.lucene.engine.transaction.support.AbstractTransactionProcessor.findByQuery(AbstractTransactionProcessor.java:146)
    at org.compass.core.lucene.engine.transaction.readcommitted.ReadCommittedTransactionProcessor.doFind(ReadCommittedTransactionProcessor.java:259)
    at org.compass.core.lucene.engine.transaction.support.AbstractConcurrentTransactionProcessor.find(AbstractConcurrentTransactionProcessor.java:246)
    at org.compass.core.lucene.engine.LuceneSearchEngine.find(LuceneSearchEngine.java:352)
    at org.compass.core.lucene.engine.LuceneSearchEngineQuery.hits(LuceneSearchEngineQuery.java:188)
    at org.compass.core.impl.DefaultCompassQuery.hits(DefaultCompassQuery.java:199)
    at grails.plugin.searchable.internal.compass.search.DefaultSearchMethod$SearchCompassCallback.doInCompass(DefaultSearchMethod.java:109)
    at org.compass.core.CompassTemplate.execute(CompassTemplate.java:133)
    at grails.plugin.searchable.internal.compass.support.AbstractSearchableMethod.doInCompass(AbstractSearchableMethod.java:56)
    at grails.plugin.searchable.internal.compass.search.DefaultSearchMethod.invoke(DefaultSearchMethod.java:71)
    at grails.plugin.searchable.SearchableService.search(SearchableService.groovy:39)
    at grails.plugin.searchable.SearchableController$_closure1.doCall(SearchableController.groovy:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    </stack-trace>
  </exception>
</error-report>
```

**Comment by dellermann** [comment]
Fixed in 2.1 by re-implementing search functionality.
