### ISSUE TITLE
Error when saving invoices with lots of items

### ISSUE THREAD

**Issue by dellermann** [dellermann/springcrm#64]
A customer reported an error which occurred when he saves an invoice with approx. 7 or more items:

``` xml
<?xml version="1.0"?>

<error-report xmlns="http://www.amc-world.de/data/xml/springcrm"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.amc-world.de/data/xml/springcrm http://www.amc-world.de/data/xml/springcrm/error-report-1.1.xsd">
  <report-version>1.1</report-version>
  <application>
    <version>1.5.2</version>
    <build-number>7831</build-number>
    <build-date>2015-01-22T18:28:14+0100</build-date>
    <build-profile>production</build-profile>
  </application>
  <customer>
    <name>Benjamin Ellermann</name>
    <email></email>
  </customer>
  <description>Hallo Dani 
immer wenn ich ca. 7 Spalten schreibe und es speichern will . kommt eine fehlermeldung und es ist alles weg .</description>
  <details>
    <status-code>500</status-code>
    <message>null id in org.amcworld.springcrm.InvoicingItem entry (don't flush the Session after an exception occurs)</message>
    <servlet>grails</servlet>
    <uri>/ungehobelt/grails/invoice/update.dispatch</uri>
  </details>
  <exception>
    <message>null id in org.amcworld.springcrm.InvoicingItem entry (don't flush the Session after an exception occurs)</message>
    <caused-by>null id in org.amcworld.springcrm.InvoicingItem entry (don't flush the Session after an exception occurs)</caused-by>
    <class-name>LruFilters</class-name>
    <line-number>60</line-number>
    <code-snippet>

    </code-snippet>
    <stack-trace>
    org.hibernate.AssertionFailure: null id in org.amcworld.springcrm.InvoicingItem entry (don't flush the Session after an exception occurs)
    at grails.orm.HibernateCriteriaBuilder.executeUniqueResultWithProxyUnwrap(HibernateCriteriaBuilder.java:141)
    at org.amcworld.springcrm.LruService.recordItem(LruService.groovy:68)
    at org.amcworld.springcrm.LruService.recordItem(LruService.groovy:51)
    at org.amcworld.springcrm.LruFilters$_closure1_closure2_closure4.doCall(LruFilters.groovy:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    </stack-trace>
  </exception>
</error-report>
```

**Comment by dellermann** [comment]
Fixed in commit db4d018.
