### ISSUE TITLE
Overview page displays error

### ISSUE THREAD

**Issue by philipdrozd** [dellermann/springcrm#67]
When displaying the overview page suddenly the following application error occurred:

``` xml
<?xml version="1.0"?>

<error-report xmlns="http://www.amc-world.de/data/xml/springcrm"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.amc-world.de/data/xml/springcrm http://www.amc-world.de/data/xml/springcrm/error-report-1.1.xsd">
  <report-version>1.1</report-version>
  <application>
    <version>1.5.3</version>
    <build-number>7838</build-number>
    <build-date>2015-08-07T13:09:19+0200</build-date>
    <build-profile>production</build-profile>
  </application>
  <customer>
    <name></name>
    <email></email>
  </customer>
  <description></description>
  <details>
    <status-code>500</status-code>
    <message>Error processing GroovyPageView: Cannot get property 'panelDef' on null object</message>
    <servlet>grails</servlet>
    <uri>/grails/overview/index.dispatch</uri>
  </details>
  <exception>
    <message>Cannot get property 'panelDef' on null object</message>
    <caused-by>Error processing GroovyPageView: Cannot get property 'panelDef' on null object</caused-by>
    <class-name>gsp_springcrm_overviewindex_gsp</class-name>
    <line-number>57</line-number>
    <code-snippet>

    </code-snippet>
    <stack-trace>
    org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Cannot get property 'panelDef' on null object
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot get property 'panelDef' on null object
    at gsp_springcrm_overviewindex_gsp$_run_closure2.doCall(gsp_springcrm_overviewindex_gsp.groovy:50)
    at gsp_springcrm_overviewindex_gsp.run(gsp_springcrm_overviewindex_gsp.groovy:78)
    ... 3 more
    </stack-trace>
  </exception>
</error-report>
```

**Comment by dellermann** [comment]
The error was caused by an invalid column/position combination. I don't know how this tuple would be produces. However, because the panel storage was completely changed in SpringCRM v2 I won't investigate further into this bug.
